# Generated by Django 2.1.1 on 2018-09-30 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_aprendiz', models.CharField(max_length=45)),
                ('identificacion', models.IntegerField()),
                ('tipo_documento', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(max_length=45)),
                ('ubicacion_bodega', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cuentadante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuentadante', models.CharField(max_length=45)),
                ('identificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado_elemento', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=1000)),
                ('tipo_daño', models.CharField(max_length=45)),
                ('fecha_limite', models.DateField()),
                ('estado_prestamo', models.CharField(max_length=45)),
                ('fecha_entrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materal', models.CharField(max_length=45)),
                ('codigo_sena', models.CharField(max_length=45)),
                ('tipo_elemento', models.CharField(max_length=45)),
                ('cantidad_material', models.IntegerField()),
                ('marca_material', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Categoria')),
                ('cuentadante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cuentadante')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('estado_prestamo', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(max_length=45)),
                ('codigo_programa', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Programa'),
        ),
        migrations.AddField(
            model_name='detalle_prestamo',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Material'),
        ),
        migrations.AddField(
            model_name='detalle_prestamo',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Prestamo'),
        ),
        migrations.AddField(
            model_name='bodega_material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Material'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='ficha',
            field=models.ManyToManyField(blank=True, null=True, to='home.Ficha'),
        ),
    ]
