# Generated by Django 2.1.1 on 2018-09-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180930_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='nombre_materal',
            new_name='nombre_material',
        ),
    ]
