# Generated by Django 2.1.1 on 2018-10-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180930_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='cantidad_material',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='marca_material',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='nombre_material',
            new_name='nombre',
        ),
    ]
