# Generated by Django 2.1.1 on 2018-10-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181002_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='cantidad',
            new_name='cantidad_material',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='marca',
            new_name='marca_material',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='nombre',
            new_name='nombre_material',
        ),
    ]
