# Generated by Django 2.1.1 on 2018-10-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181002_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='nombre_materal',
            new_name='nombre_material',
        ),
    ]
