# Generated by Django 2.1.1 on 2018-10-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181002_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega_material',
            old_name='fecha_ingreso',
            new_name='fecha_ingresa',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='estado',
            new_name='listado',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='cantidad',
            new_name='catidad',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='codigo_programa',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='aprendiz',
            name='nombre_aprendiz',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='nombre_bodega',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nombre_categoria',
        ),
        migrations.RemoveField(
            model_name='cuentadante',
            name='nombre_cuentadante',
        ),
        migrations.RemoveField(
            model_name='detalle_prestamo',
            name='estado_elemento',
        ),
        migrations.RemoveField(
            model_name='detalle_prestamo',
            name='estado_prestamo',
        ),
        migrations.RemoveField(
            model_name='detalle_prestamo',
            name='tipo_daño',
        ),
        migrations.RemoveField(
            model_name='material',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='estado_prestamo',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='nombre_programa',
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentadante',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_prestamo',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_prestamo',
            name='tipo_dano',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='marca_material',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='tipo_documento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='ubicacion_bodega',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detalle_prestamo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo_sena',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo_elemento',
            field=models.CharField(max_length=100),
        ),
    ]
