# Generated by Django 2.1.1 on 2018-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181002_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='ubicacion_bodega',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='codigo',
        ),
        migrations.AddField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
