# Generated by Django 2.0.6 on 2018-10-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181017_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo_sena',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
