# Generated by Django 2.0.6 on 2018-10-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20181021_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
