# Generated by Django 2.0.6 on 2018-10-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_material_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_prestamo',
            old_name='estado_elemento',
            new_name='estado_devolucion',
        ),
        migrations.RenameField(
            model_name='detalle_prestamo',
            old_name='estado_prestamo',
            new_name='estado_elemento_prestamo',
        ),
        migrations.RemoveField(
            model_name='detalle_prestamo',
            name='tipo_dano',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cantidad_total',
        ),
        migrations.AddField(
            model_name='detalle_prestamo',
            name='tipo_daño',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
