# Generated by Django 2.0.6 on 2018-10-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20181029_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='nombre',
            new_name='nombre_material',
        ),
    ]
