# Generated by Django 2.0.6 on 2018-10-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20181029_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='listado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='nombre_material',
            new_name='nombre',
        ),
    ]
