# Generated by Django 2.0.6 on 2018-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20181101_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_prestamo',
            name='estado_devolucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
