# Generated by Django 2.0.6 on 2018-11-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20181102_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega_material',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
